/**
 * A procedurally generated website that lives inside the crawler.
 * "The Spider Atlas": hundreds of deterministic pages with a believable
 * link graph and a sprinkling of real-world problems (broken links,
 * redirects, missing alt text, missing descriptions, orphan pages, a
 * robots.txt disallow) so every feature of Arachne has something to show,
 * even offline or when real sites refuse crawlers.
 */
export const SANDBOX_HOST = 'sandbox.arachne';
const ORIGIN = `https://${SANDBOX_HOST}`;

const SPECIES_COUNT = 360;
const FAMILIES = [
  'Araneidae', 'Salticidae', 'Theridiidae', 'Lycosidae', 'Thomisidae', 'Linyphiidae',
  'Pholcidae', 'Theraphosidae', 'Sparassidae', 'Agelenidae', 'Tetragnathidae', 'Oxyopidae',
];
const PRE = ['Silk', 'Night', 'Glass', 'Velvet', 'Ember', 'Moss', 'Iron', 'Lantern', 'Opal', 'Dusk', 'Comet', 'Thorn', 'Mirror', 'Cinder', 'Frost', 'Amber', 'Echo', 'Neon', 'Shadow', 'Copper'];
const POST = ['weaver', 'hunter', 'jumper', 'spinner', 'stalker', 'dancer', 'lurker', 'drifter', 'orb', 'trapdoor', 'sprinter', 'watcher'];
const PLACES = ['the Western Ghats', 'Borneo', 'the Atacama', 'Madagascar', 'the Andes', 'Sri Lanka', 'Tasmania', 'the Congo basin', 'Hokkaido', 'Patagonia', 'the Thar desert', 'Sumatra'];
const HABITS = [
  'builds a spiral orb web at dusk and eats it again before sunrise',
  'stalks prey across leaf litter with astonishing eyesight',
  'sails hundreds of kilometres on threads of silk caught by the wind',
  'decorates its web with zig-zag bands of ultraviolet silk',
  'hides under a hinged trapdoor of soil and silk',
  'mimics ants so convincingly that predators leave it alone',
  'vibrates its web to confuse visiting wasps',
  'carries its spiderlings on its back for weeks',
];

function rng(seed) {
  let s = seed >>> 0;
  return () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const hash = (str) => {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) h = Math.imul(h ^ str.charCodeAt(i), 16777619);
  return h >>> 0;
};
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);

function species(i) {
  const r = rng(i * 7919 + 13);
  const name = `${PRE[Math.floor(r() * PRE.length)]} ${POST[Math.floor(r() * POST.length)]}`;
  const latin = `${FAMILIES[i % FAMILIES.length].slice(0, -4)}us ${['aurelia', 'nocturna', 'vitrea', 'ignis', 'mira', 'velox', 'umbra', 'lucida'][Math.floor(r() * 8)]}`;
  return { i, name: `${name} #${i}`, slug: `${name.toLowerCase().replace(/\s+/g, '-')}-${i}`, latin, family: FAMILIES[i % FAMILIES.length], place: PLACES[Math.floor(r() * PLACES.length)], habit: HABITS[Math.floor(r() * HABITS.length)], r };
}
const speciesBySlug = (slug) => {
  const m = /-(\d+)$/.exec(slug);
  const i = m ? Number(m[1]) : -1;
  return i >= 0 && i < SPECIES_COUNT && species(i).slug === slug ? species(i) : null;
};

function layout({ title, description, body, noAlt = false }) {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${esc(title)}</title>
${description ? `<meta name="description" content="${esc(description)}">` : ''}
<meta property="og:title" content="${esc(title)}">
</head>
<body>
<header><nav>
  <a href="/">Spider Atlas</a> · <a href="/families">Families</a> · <a href="/journal">Field journal</a> · <a href="/about">About</a>
</nav></header>
<main>
${body}
${noAlt ? '<img src="/img/specimen.jpg">' : '<img src="/img/logo.png" alt="Spider Atlas logo">'}
</main>
<footer><p>The Spider Atlas is a fictional site generated by Arachne. Data on real spiders lives at <a href="https://en.wikipedia.org/wiki/Spider">Wikipedia</a> and the <a href="https://wsc.nmbe.ch/">World Spider Catalog</a>.</p></footer>
</body>
</html>`;
}

function home() {
  const r = rng(1);
  const featured = Array.from({ length: 14 }, () => species(Math.floor(r() * SPECIES_COUNT)));
  return layout({
    title: 'The Spider Atlas — a field guide to imaginary spiders',
    description: 'A sandbox website for crawling: hundreds of species pages, families and field notes.',
    body: `<h1>The Spider Atlas</h1>
<p>Welcome to the <strong>Spider Atlas</strong>, a field guide to ${SPECIES_COUNT} imaginary spiders. Every page here is generated on the fly, so you can crawl as much as you like.</p>
<h2>Families</h2>
<ul>${FAMILIES.map((f) => `<li><a href="/family/${f.toLowerCase()}">${f}</a> — ${Math.ceil(SPECIES_COUNT / FAMILIES.length)} species</li>`).join('')}</ul>
<h2>Featured species</h2>
<ul>${featured.map((s) => `<li><a href="/species/${s.slug}">${esc(s.name)}</a> <em>${esc(s.latin)}</em> from ${esc(s.place)}</li>`).join('')}</ul>
<h2>Recently in the journal</h2>
<p>Read <a href="/journal/1">the first field note</a>, browse the <a href="/journal">whole journal</a>, or download the <a href="/files/atlas-checklist.pdf">printable checklist</a>.</p>
<p>Looking for the old site? Try <a href="/old-index.html">the legacy index</a> or the <a href="/species/legacy-catalogue">legacy catalogue</a>.</p>`,
  });
}

function familyPage(name) {
  const fam = FAMILIES.find((f) => f.toLowerCase() === name);
  if (!fam) return null;
  const members = [];
  for (let i = FAMILIES.indexOf(fam); i < SPECIES_COUNT; i += FAMILIES.length) members.push(species(i));
  return layout({
    title: `${fam} — The Spider Atlas`,
    description: fam === 'Pholcidae' ? '' : `All ${members.length} species of ${fam} in the Spider Atlas.`,
    body: `<h1>${fam}</h1>
<p>The family <strong>${fam}</strong> has ${members.length} members in this atlas. Members are listed in order of discovery.</p>
<ul>${members.map((s) => `<li><a href="/species/${s.slug}">${esc(s.name)}</a> — <em>${esc(s.latin)}</em></li>`).join('')}</ul>
<p>Back to <a href="/families">all families</a>.</p>`,
  });
}

function speciesPage(s) {
  const r = s.r;
  const related = Array.from({ length: 6 }, () => species(Math.floor(r() * SPECIES_COUNT)));
  const post = 1 + Math.floor(r() * 40);
  const broken = s.i % 9 === 0 ? `<p>See also the <a href="/species/${s.slug}-photos">photo gallery</a> (moved).</p>` : '';
  return layout({
    title: s.i % 23 === 0 ? `${s.name} — ${s.latin} — a very long page title that keeps going well past what search engines will show` : `${s.name} (${s.latin})`,
    description: s.i % 5 === 0 ? '' : `${s.name}, a member of ${s.family} found in ${s.place}.`,
    noAlt: s.i % 4 === 0,
    body: `<h1>${esc(s.name)}</h1>
<p><em>${esc(s.latin)}</em> is a member of the family <a href="/family/${s.family.toLowerCase()}">${s.family}</a>, native to ${esc(s.place)}. It ${esc(s.habit)}.</p>
<table><tr><th>Family</th><td><a href="/family/${s.family.toLowerCase()}">${s.family}</a></td></tr><tr><th>Range</th><td>${esc(s.place)}</td></tr><tr><th>Leg span</th><td>${(4 + r() * 90).toFixed(1)} mm</td></tr></table>
<h2>Behaviour</h2>
<p>Field observers first described it in <a href="/journal/${post}">field note ${post}</a>. Like many relatives it ${esc(HABITS[(s.i + 3) % HABITS.length])}, and it is closely related to <a href="/species/${related[0].slug}">${esc(related[0].name)}</a>.</p>
<h2>Related species</h2>
<ul>${related.map((x) => `<li><a href="/species/${x.slug}">${esc(x.name)}</a> — ${esc(x.place)}</li>`).join('')}</ul>
${broken}
<p>Download the <a href="/files/${s.slug}.pdf">specimen sheet</a> or compare with real spiders on <a href="https://en.wikipedia.org/wiki/${encodeURIComponent(s.family)}">Wikipedia</a>.</p>`,
  });
}

function journal(n) {
  if (n === null) {
    return layout({
      title: 'Field journal — The Spider Atlas',
      description: 'Notes from imaginary expeditions.',
      body: `<h1>Field journal</h1><ul>${Array.from({ length: 40 }, (_, i) => `<li><a href="/journal/${i + 1}">Field note ${i + 1}: ${PLACES[i % PLACES.length]}</a></li>`).join('')}</ul>`,
    });
  }
  if (n < 1 || n > 40) return null;
  const r = rng(n * 104729);
  const seen = Array.from({ length: 5 }, () => species(Math.floor(r() * SPECIES_COUNT)));
  return layout({
    title: `Field note ${n} — The Spider Atlas`,
    description: n % 3 === 0 ? '' : `Expedition notes from ${PLACES[(n - 1) % PLACES.length]}.`,
    body: `<h1>Field note ${n}: ${PLACES[(n - 1) % PLACES.length]}</h1>
<p>Night ${n}. The headlamp caught a thousand tiny eyes. We logged ${seen.map((s) => `<a href="/species/${s.slug}">${esc(s.name)}</a>`).join(', ')} before the rain came.</p>
<p>${n > 1 ? `<a href="/journal/${n - 1}">← Previous note</a>` : ''} ${n < 40 ? `<a href="/journal/${n + 1}">Next note →</a>` : ''}</p>`,
  });
}

function sitemap() {
  // include a few species nothing links to: orphans only a sitemap reveals
  const urls = ['/', '/families', '/journal', '/about', ...FAMILIES.map((f) => `/family/${f.toLowerCase()}`)];
  for (let i = 0; i < SPECIES_COUNT; i += 3) urls.push(`/species/${species(i).slug}`);
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((u) => `<url><loc>${ORIGIN}${u}</loc></url>`).join('\n')}\n</urlset>`;
}

/** Serve a sandbox URL as a real fetch Response. */
export async function sandboxFetch(url) {
  const { pathname } = new URL(url);
  await new Promise((r) => setTimeout(r, 60 + (hash(pathname) % 220))); // feel like a network
  const html = (body, status = 200) => new Response(body, { status, headers: { 'content-type': 'text/html; charset=utf-8', server: 'arachne-sandbox' } });
  const redirect = (to) => new Response(null, { status: 301, headers: { location: to } });

  if (pathname === '/robots.txt') return new Response(`User-agent: *\nDisallow: /private/\n\nSitemap: ${ORIGIN}/sitemap.xml\n`, { headers: { 'content-type': 'text/plain' } });
  if (pathname === '/sitemap.xml') return new Response(sitemap(), { headers: { 'content-type': 'application/xml' } });
  if (pathname === '/' || pathname === '/index.html') return html(home());
  if (pathname === '/old-index.html') return redirect('/');
  if (pathname === '/families') return html(layout({ title: 'Families — The Spider Atlas', description: 'All spider families.', body: `<h1>Families</h1><ul>${FAMILIES.map((f) => `<li><a href="/family/${f.toLowerCase()}">${f}</a></li>`).join('')}</ul><p>Members only: <a href="/private/notes">private notes</a>.</p>` }));
  if (pathname === '/about') return html(layout({ title: 'About', description: '', body: '<h1>About</h1><p>Contact the curators at curators@sandbox.arachne. This site exists so crawlers have a safe place to play.</p>' }));
  if (pathname === '/journal') return html(journal(null));
  let m;
  if ((m = /^\/journal\/(\d+)$/.exec(pathname))) {
    const page = journal(Number(m[1]));
    if (page) return html(page);
  }
  if ((m = /^\/family\/([a-z]+)$/.exec(pathname))) {
    const page = familyPage(m[1]);
    if (page) return html(page);
  }
  if ((m = /^\/species\/([a-z0-9-]+)$/.exec(pathname))) {
    const s = speciesBySlug(m[1]);
    if (s) return html(speciesPage(s));
    if (m[1] === 'legacy-catalogue') return redirect('/families');
  }
  if (pathname.startsWith('/files/')) return new Response('%PDF-1.4 sandbox', { headers: { 'content-type': 'application/pdf' } });
  return html(layout({ title: '404 — Lost in the web', description: '', body: `<h1>404: this thread leads nowhere</h1><p>The page <code>${esc(pathname)}</code> was eaten. Try the <a href="/">home page</a> or <a href="/families">families</a>.</p>` }), 404);
}
